"""consulta_response

Revision ID: 1c84ec8ae46e
Revises: f5e556203663
Create Date: 2026-05-25 22:22:16.476344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c84ec8ae46e'
down_revision: Union[str, None] = 'f5e556203663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('consultas', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'responded_at')
    op.drop_column('consultas', 'response')
    # ### end Alembic commands ###
